name: zachetka_student
description: "Зачётка · Студент — просмотр успеваемости. Вход и данные через Firebase."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
